apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: external-secrets
  podMetricsEndpoints:
    - port: metrics
