---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgBX6UhwmGTk71Jy6p93cn1L9LckeIMbDZ42nhH7dVtavUQMP7Dmz9ZUeDq7WkrrEdS3qG4ibDAy9il7BjxzZbuY5mfs4xq1l2rLCu/Eeazi8WgZiPnBtjDPPAPnkfvjjX4cvPjLXUSE0zjr+cjIoCSWjQ1EFzafmys2Rnk8lS8/dPxA2I5suXJi0ag3U2QIlGCQ/ejcT7sEoFWQkuEQj6NPUOQyeSwhxQgfQDq3kZafEDjaHkXjrvKmYVBGaHaiQ+LddtE6QcYX/vCUbppq3TNvPYXY1JfiMW7/pJUCHJwkBiY0O8LxCNAtCx3D9W+4KvVvC5OkvfDs1yqteKFGzOKfHm5KWT2KMLE9WnPSempcDpPv21wCBz/TMJ5EKVY1VsO7m5QjHj9UG72oHxY1rtf8CeASPkMzyhG0QusMU2dj430EXUOX2PbHYCp/eG06i2NMgNy6jIJTwbBP3ysIckfMTWDNJdo7yFrTfnOaZeMPfNQtewkudMKdnSSZR5qeVBW6o0X/aga0H54fdvFCEledfcDumlFL2EP8AZ9CD4Okz/kSPSbQqasgIKhhGynHMaGa1F10OPPLiHKvpnCsi/egfXXgJCS1VBud9keNVffJWXcIFP8TzAvCKdnTMvtLCc0HG/D9EOYtuWjpmsQ9YoV6+iWM6/kIym+ieMvTviNBCu1l9K6JNOALuRdFAGnftBGk8uete1XZ78olFKUjLI4REXJ1++v6+pUWtuZij2Z+PeJR3q2LdK/Rzp/cMIgV+pSHmarq5bBt3VAXiTdu62NkeW5WrNuyZ2VaIQxvyqaGWL7jn3hfq1jrtMyvVYpoy7rvXB5WAhiyVkre87x60WdGiQlkBzhcYcRhuXVKM5gPcU6iWPItTDnHiHZR3SkaOYla/tu7lsGNcaoTRw22kBIfhiNByjICDHZHpSN5CrRZ
  template:
    metadata:
      name: cloudflared-credentials
      namespace: cloudflared
