---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-secret
  namespace: forgejo
spec:
  encryptedData:
    FORGEJO__security__INTERNAL_TOKEN: AgBEHCnQfGbdntn8wjB6RD0ro9i1TE6JGl76WNsONRmLEA1r9ql58XOdwOh02AK9sDqhIgQHrRoQO+YpcZITUsvhVwUb3xefblj3VN2r3exZmOOB3rrYuZfqlE0ofD5hmgw+usXkVVNU9vCHJzsEMvDEsPZ96Mg5cQ7NRNJUiQIy4n9IiqArKKIwQawC8knFkEhDTeayonVl+lxbeCX7LZFGh9oATmv7iL2LbSf+4JOnpDwwXa6A1QAN55EAmE0AsSyat7DB9OqEZFTIT+ssteXcgzSWbqabHU3wwj6/ZBM0ldivTNswrLrP+2/RV2PYPpqs5M7dCoAsOfZYC5XJJFYh9HkeA0HMOHsiUluzDN/5BSoMhkHQGpNJ6a5OX6j+LcBuO4ZEav1zvv9winvZSo5A5JNfcuHHq6/lAqgNqS9nAGzUU2FmHGbRezmYv+T3ItMWUvdg4+VBxD7sVpIt5zPZ+ZpcIYZu1Qy7iokKf3M/9cM5YNO6OUo0qrelX/vY0hl0+m0Kk1z/TCDZbwdnRkNLIoBw7hNHI2ZiFEW8OsOZm04C1IspCOhyC0KeAlQ/ylajJ4Dg5AiRVTKzt7Nq4DLl+fnXegScUpkcwhdU6OA+UK/NZIw/qG7dfcsxPzeLU8iJPInnrysVyhWXmMvBHN8pwCal+I6sbEL+u/uig8BPtMPmlXFR5Jk8vft+ndDk2I01z6Au3xwdH6FaTyCk7I+IzzD4Icj/0YSakk4kA91Qs7ZVMLnQkfAZdBLUifVBCuCXis2KaFOD5s7afVz2xxcv2e/iN84ExlFxVGEqCkrkdwkqooJKHDB6Iwz0fhT1ZF2oHf5LU4O1BGg=
    FORGEJO__security__SECRET_KEY: AgCpEsrQ/PKeJlB0ab0nzRCXCS9zvoJw7koDOqmtgEg17yfrMJ233pbJmlvjEx6k5kXBh7AzOC3pdbMvb0rOtMOvEaxtThkdjmz9puu4MmerUnoz6A+s0JYrL4q21R4tFjMGfDYY7Oi2+Cmt5moqmzBdipsEttZzsSlG9JIxxAitVmp6p5Lk6Ltn6sQsK4GRbFIyzhaIIzt5uxY4nor+zkTBTqYi9dAW41zUXXE/Eg2ZZ7vOPrFMpsaooaEMapMXRePfKgfqRDbL/Dx4BwwFiyUAx/cSq+9vD1/hQlnDi9DbdM4bmiuISOSiB+NZCtI+sNvQTxd4YPLPDjWrGRhQ8VnxRkAyztgBbSYgb38WpEccArEJLo0DVdU4clEggxJ7Xw+XXc6y9N69TcQX9wD4MgNnXWcvhJsKk7S0vQXPAuNr0UwoUeK57rAqVTxTxvDPMMfIFRFyUUyuhn0SvAM30SmqFSsnzld1F4XTGYLCbYy6GlbE9Gcm/8/jBJuYPDgIVdXPYaWViQnVC1alNDrxOGf9btW3KNX+tneL6pZqHDE7pTp2lBZAArgA+sfoTZeEN932SY4NaLls2lP7VrIRtODNi3CLeRRELmRH4hbgR5wy+2udXayRKRl85DM1h0prpjn6ABkvm/+yMitQRagc6f9vWPzl1/F5AoZ7/POGzozpPK1O+BFRucAZzUppPQGcxlqL4opYzNhu6s1F4nFbC0xap3lftn+9jkAP4L4vaBu4OdrafcWJ/hs4M/1t
  template:
    metadata:
      name: forgejo-secret
      namespace: forgejo
    type: Opaque
