apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vmks-grafana-admin
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: vmks-grafana-admin
  data:
    - secretKey: admin-user
      remoteRef:
        key: /bons8i/monitoring/vmks-grafana-admin/admin-user
    - secretKey: admin-password
      remoteRef:
        key: /bons8i/monitoring/vmks-grafana-admin/admin-password
