apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vmbackup-aws-credentials
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: vmbackup-aws-credentials
  data:
    - secretKey: access-key-id
      remoteRef:
        key: /bons8i/monitoring/vmbackup/access-key-id
    - secretKey: secret-access-key
      remoteRef:
        key: /bons8i/monitoring/vmbackup/secret-access-key
