apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-to-github
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: alertmanager-to-github
  data:
    - secretKey: github-token
      remoteRef:
        key: /bons8i/monitoring/alertmanager-to-github/github-token
