---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-to-github
  namespace: monitoring
spec:
  encryptedData:
    github-token: AgAutWErQNaQR9dqgttW3tcbWJTOkt6N9gK0Yq+tlLmGEq8QRWocQQT+iJ3qF3TNCgjnyuUPMplrjbjw1pUlRELfVcfa0twkaRcrg1rzBN8r/cgPx9Gs7HlcP7KxJ0tLWIe9m2PptuIJxtB6yswmZ27lcA/elEmQou3JZTsrLPMaDSb/91hJx8EV2QsMMEh35PbNS1TLaQXH6WLmme/XotysW9Gz1EBGj6uI3Vfczs9UrDaufY3sJJhTNNQnOtSSjXw4pKqnVxM5TFz5LezYKWHyKY94Xb7JY0SeReWhhjmAszwZeUtfd9puPhk3rXyXCV7nx82w6RgGfv9c57QneXle70I83oXgBPfYXddyi36jYQPwXyB7B78LONotWGY/IHf6MQpUH+PQEZ3O03P7hJPRg8LTlt6Owbny11a3oSCb6CGvuM32BRlHM1/yoKywC3u8khEX6epAnamG8I1CFJv/8G0f+zkEq1htqgMorTLDOxZ4jauBg7CFILU6J6Kaw5D+rnyFdQnJdbFOu1EYKacINnC8BtswFrSSCAo63vPHyJykIS9Pj7Zl6+nCpsy3P+TPzXYC8O+lOSfdIROgrkuOglDZsYtxpdKPF2HWeTDXJcBvHlKfYaNrgQNakhEw6es4okBPwTaczwyj96F3aFmWEVw0kTEgeymHDog+tzLuTbrHcOVCzanKZHu6vV1gCOvSvq8Ki7D2ZS1CG9Q5YLNit1DpmNRYVMdtF7zqIaPqdcP2/z7i69QfupeJTwsXuV8pzjAwUGUk+Y6hyUI81QdskbU8RZeVpy2MAd1IVNXcdT0PY3FM3v0XN2ckQYA=
  template:
    metadata:
      name: alertmanager-to-github
      namespace: monitoring
