---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vmks-grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgA08x54MXZ+uvm19kXQJphe55X8ZdLY5KbPdZ7KyEgGVlU+3oUns2AcJ2k7dRhxNmB/l4EBtTdv2oNxudC3st5iEOJR/HTrFQP7BXndlqjAe7Fxnhy3QuRCzNh0fktG22UKr3H8Q2Cz9D1j53uiVZ22DipK+mheZkvsDpOpqBBakC77+IoXESc9UtfS66jpbQffJlLxZBtkCkORKehgAl2KehMORpkZAre3NUUCrSR4MVfRz2fowwseNlodHIlAkkk8bvNh3G9h2sKF0xZdS5ClocNMYMXE34L0XVnrE70ASNNcB39o+8hBUYWM+lSsXwaQ6iNy4JVMAJdMRBWev8l32j2Banpc/g5G3+A8tcD7NctJjLush/w1kUIUW/S53E7xN6cS0U21aun1akpMCcAKUSurSE8DnQyGbt3HzE9bBixKvLlaXLgwBEUVuuxP1w//DFuoRj25Ke+Ga+atGdCutLbe+FLmdxi+qhcqWWfQ4q4NbtNLqk4qdRCHZsF5YyMCE4eIrWO8/NxCgspXbU90TrdupKeZg0NfFyqQItyHCLLh/iKgPbiB3eozLA0qQPPgHEMvkglcmSpQXW891+EZCa9kr9CzVc1y6Gqw79JUek3mqg/SZeCZVz4G+F6uD3+Ohr43M+2nuMNGonfznanI3ZLNNNkJrPQ/CjtMu/uotljq9WgrBj7DvY1RXrK+F6QjaLW15Pa9olhTrd6Rrv6oOBOFhbdRJZrlkkO+2iTMpw==
    admin-user: AgCIqmnBytk4nfIiFV7jOv7OvAIoo59PeUA7NlU2MQg2qw0W4ROD93vohsMlCK5P2OC1A0Ljl7unk8o4uCxi7m8XwNQg3vTadsnRMJnJllnkWRXiJNUeM7EbabmpfhEqmcmjdY8j8sv4A7Q6hz0xzCyjJ/3Lnweo6T9cRZNUKXvpHYcal171hnjRVu5FHtKxLO5pHIN6I5VmlLC+jjaWq8/kSwY5DNmWtFKAhncVGxhbbrnry+keTvTfQeTRqXXEKAR4zGtHRceKmddRkHq4R2Ak7BWSAvd0DmiMUB0feeh7XHooVqwGOhxluc4/AsmS8gck2hf/PawdnHxj6eO0YldGNo/R6GKuuTxeCQBvooGpTgbKrqu7aFzBagJ/iFqxhPA+WQyEDo7VW4aAFh+4BKWo8YGRTwwIF83z8wMOlQ6yftApjq+SuLMCiH4Es3U8dGDvDaKmxaMGIV57guMKINRlHEuYxltKFqcZmXsqmixVK8tq+fXRgvxsy7WzUnbmiwUUZ2VdwNUlUV/x/pD5RsvMsIfUqtCzEWLllNb0HbFOc2GiQH1xbTUzAQyTYVnDfMtRI6eNqRLAEOLWftKnZ88m1yWX6U9JI9FcqSUwssJvNlVSTexC4eTLbx4FABpYfYq+ZBS3rZKlSIssurseqHEJ4vPneBfohyrVrdMTYIFQxpt2e2//JxEf6oPy8tYNKefJtMUoog==
  template:
    metadata:
      name: vmks-grafana-admin
      namespace: monitoring
