apiVersion: v1
kind: ServiceAccount
metadata:
  name: alertmanager-to-github
  namespace: monitoring
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vmbackup
  namespace: monitoring
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vm-archive
  namespace: monitoring
automountServiceAccountToken: false
