apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forgejo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/HagaSpa/bons8i.git
    targetRevision: main
    path: clusters/pi/forgejo
  destination:
    server: https://kubernetes.default.svc
    namespace: forgejo
