apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- serviceaccount.yaml
- networkpolicy.yaml

images:
- name: ghcr.io/hagaspa/bons8i/status-page
  newTag: b7527ca59ac423b37c80f681317674b88bf505de
