apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- serviceaccount.yaml
- networkpolicy.yaml

images:
- name: ghcr.io/hagaspa/bons8i/status-page
  newTag: b29f82e196a8d9af5b17f4918f6ae41e3c3f9301
