apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- serviceaccount.yaml
- networkpolicy.yaml

images:
- name: ghcr.io/hagaspa/bons8i/status-page
  newTag: 9bef8904927c8b67c1dfbf4e7927650317a16771
